# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 01:51
from __future__ import unicode_literals
from django.db import migrations
import csv



def load_user_data(apps, schema_editor):
    Rater = apps.get_model('lensview', 'Rater')

    with open('/Users/JonathanKross/tiy/assignments/django-movies/ml-1m/users.dat') as f:
        reader = csv.DictReader([line.replace('::', '\t') for line in f],
        fieldnames='UserID::Gender::Age::Occupation::Zip-code'.split('::'),
        delimiter='\t'
        )

    for row in reader:
        r = Rater(gender=row['Gender'], age=row['Age'],
            occupation=row['Occupation'], zipcode=row['Zip-code'])
        r.save()



class Migration(migrations.Migration):

    dependencies = [
        ('lensview', '0002_auto_20160505_0130'),
    ]

    operations = [
        migrations.RunPython(load_user_data),
    ]
