# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 03:23
from __future__ import unicode_literals
from django.db import migrations
import csv


def load_user_data(apps, schema_editor):
    Rater = apps.get_model('lensview', 'Rater')

    with open('/Users/JonathanKross/tiy/assignments/django-movies/ml-1m/users.dat') as f:
        reader = csv.DictReader([line.replace('::', '\t') for line in f],
        fieldnames='UserID::Gender::Age::Occupation::Zip-code'.split('::'),
        delimiter='\t'
        )

    for row in reader:
        r = Rater(id=row['UserID'], gender=row['Gender'], age=row['Age'],
            occupation=row['Occupation'], zipcode=row['Zip-code'])
        r.save()


def load_movie_data(apps, schema_editor):
    Movie = apps.get_model('lensview', 'Movie')

    with open('/Users/JonathanKross/tiy/assignments/django-movies/ml-1m/movies.dat', encoding='windows-1252') as f:
        reader = csv.DictReader([line.replace('::', '\t') for line in f],
        fieldnames='MovieID::Title::Genres'.split('::'),
        delimiter='\t'
        )

    for row in reader:
        m = Movie(id=row['MovieID'], title=row['Title'], genre=row['Genres'])
        m.save()


def load_rating_data(apps, schema_editor):
    Movie = apps.get_model('lensview', 'Movie')
    Rater = apps.get_model('lensview', 'Rater')
    Rating = apps.get_model('lensview', 'Rating')

    with open('/Users/JonathanKross/tiy/assignments/django-movies/ml-1m/ratings.dat') as f:
        reader = csv.DictReader([line.replace('::', '\t') for line in f],
        fieldnames='UserID::MovieID::Rating::Timestamp'.split('::'),
        delimiter='\t'
        )

    for row in reader:
        r = Rating(rater=Rater.objects.get(id=row['UserID']),
                    movie=Movie.objects.get(id=row['MovieID']),
                    stars=row['Rating'])
        r.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lensview', '0004_auto_20160505_0216'),
    ]

    operations = [
        migrations.RunPython(load_user_data, load_movie_data, load_rating_data)
    ]
