# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 17:45
from __future__ import unicode_literals
from django.db import migrations
import csv


def load_movie_data(apps, schema_editor):
    Movie = apps.get_model('lensview', 'Movie')

    with open('../../../ml-1m/movies.dat', encoding='windows-1252') as f:
        reader = csv.DictReader([line.replace('::', '\t') for line in f],
        fieldnames='MovieID::Title::Genres'.split('::'),
        delimiter='\t'
        )

    for row in reader:
        m = Movie(id=row['MovieID'], title=row['Title'], genre=row['Genres'])
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lensview', '0005_auto_20160505_0323'),
    ]

    operations = [
        migrations.RunPython(load_movie_data)

    ]
