# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 17:46
from __future__ import unicode_literals
from django.db import migrations
import csv


def load_rating_data(apps, schema_editor):
    Movie = apps.get_model('lensview', 'Movie')
    Rater = apps.get_model('lensview', 'Rater')
    Rating = apps.get_model('lensview', 'Rating')

    with open('../../../ml-1m/ratings.dat') as f:
        reader = csv.DictReader([line.replace('::', '\t') for line in f],
        fieldnames='UserID::MovieID::Rating::Timestamp'.split('::'),
        delimiter='\t'
        )

    for row in reader:
        r = Rating(rater=Rater.objects.get(id=row['UserID']),
                    movie=Movie.objects.get(id=row['MovieID']),
                    stars=row['Rating'])
        r.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lensview', '0006_auto_20160505_1745'),
    ]

    operations = [
        migrations.RunPython(load_rating_data)
    ]
