# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lensview', '0008_auto_20160506_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='average_rating',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='number_ratings',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating_sum',
            field=models.IntegerField(default=-1),
        ),
    ]
