# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 19:12
from __future__ import unicode_literals

from django.db import migrations
from lensview.models import Movie

def populate_num_ratings(apps, schema_editor):
    movies = Movie.objects.all()
    for movie in movies:
        num_ratings = len(movie.rating_set.all())
        movie.number_ratings = num_ratings
        movie.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lensview', '0009_auto_20160506_1911'),
    ]

    operations = [
        migrations.RunPython(populate_num_ratings)
    ]
