# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 19:22
from __future__ import unicode_literals

from django.db import migrations
from lensview.models import Movie
from django.db.models import Sum

def populate_sum_column(apps, schema_editor):
    movies = Movie.objects.all()
    for movie in movies:
        if movie.number_ratings == 0:
            movie.rating_sum = 0
            movie.save()
        else:
            sum_ratings = movie.rating_set.all().aggregate(Sum('stars'))
            movie.rating_sum = sum_ratings['stars__sum']
            movie.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lensview', '0010_auto_20160506_1912'),
    ]

    operations = [
        migrations.RunPython(populate_sum_column)
    ]
