# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 19:38
from __future__ import unicode_literals

from django.db import migrations
from lensview.models import Movie
from django.db.models import Avg


def populate_avgerage_column(apps, schema_editor):
    movies = Movie.objects.all()
    for movie in movies:
        if movie.number_ratings == 0:
            movie.average_rating = 0
            movie.save()
        else:
            avg_ratings = movie.rating_set.all().aggregate(Avg('stars'))
            movie.average_rating = avg_ratings['stars__avg']
            movie.save()

class Migration(migrations.Migration):

    dependencies = [
        ('lensview', '0011_auto_20160506_1922'),
    ]

    operations = [
        migrations.RunPython(populate_avgerage_column)
    ]
