# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 19:37
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import User
from lensview.models import Rater

def create_rater_users(apps, schema_editor):
    raters = Rater.objects.all()
    for rater in raters:
        username = 'rater' + str(rater.id)
        email = 'rater' + str(rater.id) + '@raters.com'
        password = 'rater' + str(rater.id) + 'password'
        user = User.objects.create_user(username, email, password)

class Migration(migrations.Migration):

    dependencies = [
        ('lensview', '0014_auto_20160507_1823'),
    ]

    operations = [
        migrations.RunPython(create_rater_users)
    ]
