# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 00:29

from __future__ import unicode_literals
from django.db import migrations
from lensview.models import Rater
from django.contrib.auth.models import User


def update_rater_user(apps, schema_editor):
    raters = Rater.objects.all()
    for rater in raters:
        u = User.objects.get(username='rater{}'.format(rater.id))
        rater.user = u
        rater.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lensview', '0015_auto_20160507_1937'),
    ]

    operations = [
        migrations.RunPython(update_rater_user)
    ]
